# Generated by Django 4.1.5 on 2023-03-23 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='added',
            name='send_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='images',
            name='added_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
