# Generated by Django 4.1.5 on 2023-03-19 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='level_autumn',
        ),
        migrations.RemoveField(
            model_name='level',
            name='level_spring',
        ),
        migrations.RemoveField(
            model_name='level',
            name='level_summer',
        ),
        migrations.RemoveField(
            model_name='level',
            name='level_winter',
        ),
        migrations.AddField(
            model_name='level',
            name='autumn',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='level',
            name='spring',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='level',
            name='summer',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='level',
            name='winter',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
