# Generated by Django 4.1.5 on 2023-03-20 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0002_remove_level_level_autumn_remove_level_level_spring_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='added',
            old_name='coord_id',
            new_name='coords',
        ),
        migrations.RenameField(
            model_name='added',
            old_name='level_id',
            new_name='level',
        ),
    ]
