# Generated by Django 4.1.5 on 2023-03-20 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0003_rename_coord_id_added_coords_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='added',
            name='add_time',
            field=models.DateTimeField(),
        ),
    ]
