# Generated by Django 4.1.5 on 2023-03-19 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0003_alter_added_connect'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='foto',
            new_name='data',
        ),
    ]
