# Generated by Django 4.1.5 on 2023-03-20 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0004_alter_added_add_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='added',
            name='send_time',
            field=models.DateTimeField(auto_now_add=True, default='2023-03-20 09:48:51.196840'),
            preserve_default=False,
        ),
    ]
